[workspace]
resolver = "2"
members = ["rs-lib", "wasm"]

[workspace.dependencies]
reqwest = "^0.12.18"
serde = "^1.0.219"
serde_json = "^1.0.140"

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"
