name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # Matches tags like 1.0.0, 0.2.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for changelog generation if using tools like release-please or conventional-changelog

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Change to jsr directory
        run: cd jsr

      - name: Jsr publish
        run: deno publish

  npm:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.5

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Change to npm directory
        run: cd npm

      - name: Build
        run: deno task build

      - name: Change to npm directory
        run: cd .npm

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ".npm/**"
          token: ${{ secrets.GITHUB_TOKEN }}
